# Generated by Django 3.2.7 on 2021-09-17 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churrasco', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receita',
            new_name='Churrasco',
        ),
    ]
