# Generated by Django 3.2.7 on 2021-09-17 19:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('churrasco', '0002_rename_receita_churrasco'),
    ]

    operations = [
        migrations.AddField(
            model_name='churrasco',
            name='autor',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='churrasco',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='churrasco',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='churrasco',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='churrasco',
            name='date_receita',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='churrasco',
            name='ingredientes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='churrasco',
            name='modo_preparo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='churrasco',
            name='nome_receita',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='churrasco',
            name='rendimento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='churrasco',
            name='tempo_preparo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
