# Generated by Django 3.2.7 on 2021-09-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churrasco', '0004_auto_20210917_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='churrasco',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Capa do Post'),
        ),
    ]
